services:
  postgres:
    image: postgres:15
    container_name: event_clean
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gym
    ports:
      - "5431:5432"